# version: "3.8"
#networks:
#  online_judge:
#    driver: bridge

services:
  mysql:
#    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: onlinejudge
      TZ: Asia/Shanghai
    ports:
      - "3307:3306"
#    networks:
#      - online_judge
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
#    container_name: redis
    image: redis:latest
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6380:6379"
#    networks:
#      - online_judge
    volumes:
      - redis_data:/data

  etcd:
    container_name: etcd
    image: "quay.io/coreos/etcd:v3.5.5"
    restart: on-failure
    privileged: true
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - ETCD_API=3
      - ETCD_CERT_FILE="/path/to/server.crt"
      - ETCD_KEY_FILE="/path/to/server.key"
      - ETCD_AUTH="simple"
      - ETCD_AUTH_USER="online_judge"
      - ETCD_AUTH_PASSWORD="online_judge"
    ports:
      - "2380:2379"
#    networks:
#      - online_judge

  etcd-keeper:
    image: "evildecay/etcdkeeper:latest"
    container_name: etcd-keeper
    environment:
      - ETCD_HOSTS=http://etcd:2379
      - SW_STORAGE_ETCD_CLUSTER_NODES=etcd:2379
      - HOST=127.0.0.1
      - HOSTNAME=etcd-keeper
    links:
      - etcd
    ports:
      - "8085:8080"
#    networks:
#      - online_judge

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5673:5672" # AMQP 端口
      - "15673:15672"  # 管理界面端口
    environment:
      - RABBITMQ_DEFAULT_USER=guest # 设置 RabbitMQ 默认用户名
      - RABBITMQ_DEFAULT_PASS=guest # 设置 RabbitMQ 默认密码
#    networks:
#      - online_judge

  online_judge:
    build: .
    environment:
      TZ: Asia/Shanghai
    ports:
      - "65533:65533"
    depends_on:
      - mysql
      - redis
      - etcd
      - etcd-keeper
      - rabbitmq
    command: sh -c "./app/wait-for-it.sh mysql:3306 redis:6380 rabbitmq:5673 etcd:2380 etcd-keeper:8085 -- nohup ./judgement & ./online_judge"
#    command: [
#
#
#        #      "/app/wait-for-it.sh", "mysql:3306", "--timeout=30", "--",
#      "/app/wait-for-it.sh", "redis:6379", "--",
#      "/app/wait-for-it.sh", "rabbitmq:5672", "--",
#      "/app/wait-for-it.sh", "etcd:2379", "--",
#      "sh", "-c", "nohup ./judgement & ./online_judge"
#    ]

volumes:
  mysql_data:
  redis_data: