# version: "3.8"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: OnlineJudge
      TZ: Asia/Shanghai
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  redis:
    image: redis:latest
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
  onlinejudge:
    build: .
    environment:
      TZ: Asia/Shanghai
    ports:
      - "65533:65533"
    depends_on:
      - mysql
      - redis
    command: ["/app/wait-for-it.sh", "mysql:3306", "--", "/app/wait-for-it.sh", "redis:6379", "--", "./OnlineJudge"]
volumes:
  mysql_data:
  redis_data:
