basePath: /api/v1
definitions:
  controller._Response:
    properties:
      code:
        type: integer
      data:
        description: omitempty 字段为空就忽略
      msg: {}
    type: object
host: 127.0.0.1:65533
info:
  contact:
    email: support@swagger.io
    name: Eutop1a
    url: http://www.swagger.io/support
  description: Refactoring
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: online-judge
  version: "1.0"
paths:
  /admin/problem/{problem_id}:
    delete:
      consumes:
      - multipart/form-data
      description: 删除题目接口
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 题目ID
        in: path
        name: problem_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 删除题目
      tags:
      - Admin API
    put:
      consumes:
      - multipart/form-data
      description: 更新题目信息接口
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 题目ID
        in: path
        name: problem_id
        required: true
        type: string
      - description: 题目标题
        in: formData
        name: title
        type: string
      - description: 题目内容
        in: formData
        name: content
        type: string
      - description: 题目难度
        in: formData
        name: difficulty
        type: string
      - description: 时间限制
        in: formData
        name: max_runtime
        type: string
      - description: 内存限制
        in: formData
        name: max_memory
        type: string
      - collectionFormat: multi
        description: 测试样例集
        in: formData
        items:
          type: string
        name: test_cases
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 更新题目信息
      tags:
      - Admin API
  /admin/problem/create:
    post:
      consumes:
      - multipart/form-data
      description: 创建新题目接口
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 题目标题
        in: formData
        name: title
        required: true
        type: string
      - description: 题目内容
        in: formData
        name: content
        required: true
        type: string
      - description: 题目难度
        in: formData
        name: difficulty
        required: true
        type: string
      - description: 时间限制
        in: formData
        name: max_runtime
        required: true
        type: integer
      - description: 内存限制
        in: formData
        name: max_memory
        required: true
        type: integer
      - collectionFormat: multi
        description: 测试样例集
        in: formData
        items:
          type: string
        name: test_cases
        required: true
        type: array
      produces:
      - application/json
      - multipart/form-data
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 创建新题目
      tags:
      - Admin API
  /admin/users/{user_id}:
    delete:
      consumes:
      - multipart/form-data
      description: 删除用户接口
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 删除用户
      tags:
      - Admin API
  /admin/users/add-admin:
    post:
      consumes:
      - multipart/form-data
      description: 添加管理员接口
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 添加管理员
      tags:
      - Admin API
  /admin/users/add-super-admin:
    post:
      consumes:
      - multipart/form-data
      description: 添加超级管理员接口
      parameters:
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      - description: 密钥
        in: formData
        name: secret
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 添加超级管理员
      tags:
      - Admin API
  /check-picture-code:
    post:
      consumes:
      - multipart/form-data
      description: 检查图片验证码
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 图片验证码
        in: formData
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 检查图片验证码
      tags:
      - Verification Code API
  /leaderboard/user:
    get:
      consumes:
      - multipart/form-data
      description: 获取用户题解排名接口
      produces:
      - application/json
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 获取用户题解排名
      tags:
      - Rank API
  /login:
    post:
      consumes:
      - multipart/form-data
      description: 用户登录接口
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      - text/xml
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 用户登录
      tags:
      - User API
  /problem/{problem_id}:
    get:
      consumes:
      - multipart/form-data
      description: 获取单个题目详细接口
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 题目ID
        in: path
        name: problem_id
        required: true
        type: string
      produces:
      - application/json
      - multipart/form-data
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 获取单个题目详细
      tags:
      - Problem API
  /problem/id:
    post:
      consumes:
      - multipart/form-data
      description: 获取题目ID接口
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 标题
        in: formData
        name: title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 题目title不存在
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 获取题目ID
      tags:
      - Problem API
  /problem/list:
    get:
      description: 获取题目列表接口
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 获取题目列表
      tags:
      - Problem API
  /register:
    post:
      consumes:
      - multipart/form-data
      description: 用户注册接口
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      - description: 验证码
        in: formData
        name: code
        required: true
        type: string
      produces:
      - application/json
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 用户注册
      tags:
      - User API
  /send-email-code:
    post:
      consumes:
      - multipart/form-data
      description: 发送邮箱验证码接口
      parameters:
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 发送邮箱验证码
      tags:
      - Verification Code API
  /send-picture-code:
    post:
      consumes:
      - multipart/form-data
      description: 发送图片验证码接口
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 发送图片验证码
      tags:
      - Verification Code API
  /submissions/code:
    post:
      consumes:
      - multipart/form-data
      description: 提交代码接口
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户id
        in: formData
        name: user_id
        required: true
        type: string
      - description: 题目id
        in: formData
        name: problem_id
        required: true
        type: string
      - description: 语言
        in: formData
        name: language
        required: true
        type: string
      - description: 代码
        in: formData
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 提交代码
      tags:
      - Submission API
  /user-id:
    post:
      consumes:
      - multipart/form-data
      description: 获取用户ID接口
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 用户名不存在
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 获取用户ID
      tags:
      - User API
  /users/{user_id}:
    get:
      consumes:
      - multipart/form-data
      description: 获取用户详细信息接口
      parameters:
      - description: 用户ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 获取用户详细信息
      tags:
      - User API
    put:
      consumes:
      - multipart/form-data
      description: 更新用户详细信息接口
      parameters:
      - description: 用户ID
        in: path
        name: user_id
        required: true
        type: string
      - description: 用户密码
        in: formData
        name: password
        type: string
      - description: 用户邮箱
        in: formData
        name: email
        type: string
      - description: 邮箱验证码
        in: formData
        name: code
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 更新用户详细信息
      tags:
      - User API
swagger: "2.0"
