basePath: /api/v1
definitions:
  controller._ResponseRegister:
    properties:
      error: {}
      msg: {}
      token:
        type: string
    type: object
  controller._ResponseSendCode:
    properties:
      msg:
        type: string
    type: object
host: 127.0.0.1:65533
info:
  contact:
    email: support@swagger.io
    name: Eutop1a
    url: http://www.swagger.io/support
  description: Refactoring
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: OnlineJudge
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - multipart/form-data
      description: 用户登录接口
      parameters:
      - description: 用户名
        in: formData
        name: user_name
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      - description: 验证码
        in: formData
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            $ref: '#/definitions/controller._ResponseRegister'
        "400":
          description: 用户名不存在或验证码错误
          schema:
            $ref: '#/definitions/controller._ResponseRegister'
        "401":
          description: 验证码过期
          schema:
            $ref: '#/definitions/controller._ResponseRegister'
        "403":
          description: 密码错误
          schema:
            $ref: '#/definitions/controller._ResponseRegister'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._ResponseRegister'
      summary: 用户登录
  /register:
    post:
      consumes:
      - multipart/form-data
      description: 用户注册接口
      parameters:
      - description: 用户名
        in: formData
        name: user_name
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      - description: 验证码
        in: formData
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            $ref: '#/definitions/controller._ResponseRegister'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller._ResponseRegister'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/controller._ResponseRegister'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller._ResponseRegister'
      summary: 用户注册
  /sendCode:
    post:
      consumes:
      - multipart/form-data
      description: 发送验证码接口
      parameters:
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 发送验证码成功
          schema:
            $ref: '#/definitions/controller._ResponseSendCode'
        "400":
          description: 邮箱格式错误
          schema:
            $ref: '#/definitions/controller._ResponseSendCode'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._ResponseSendCode'
      summary: 发送验证码
swagger: "2.0"
