basePath: /api/v1
definitions:
  controller._Response:
    properties:
      code:
        type: integer
      data:
        description: omitempty 字段为空就忽略
      msg: {}
    type: object
host: 127.0.0.1:65533
info:
  contact:
    email: support@swagger.io
    name: Eutop1a
    url: http://www.swagger.io/support
  description: Refactoring
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: online-judge
  version: "1.0"
paths:
  /check-picture-code:
    post:
      consumes:
      - multipart/form-data
      description: 检查图片验证码
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 图片验证码
        in: formData
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 检查图片验证码
  /login:
    post:
      consumes:
      - multipart/form-data
      description: 用户登录接口
      parameters:
      - description: 用户名
        in: formData
        name: user_name
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      - description: 验证码
        in: formData
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 用户登录
  /register:
    post:
      consumes:
      - multipart/form-data
      description: 用户注册接口
      parameters:
      - description: 用户名
        in: formData
        name: user_name
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      - description: 验证码
        in: formData
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 用户注册
  /send-code:
    post:
      consumes:
      - multipart/form-data
      description: 发送图片验证码接口
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 发送图片验证码
  /send-email-code:
    post:
      consumes:
      - multipart/form-data
      description: 发送邮箱验证码接口
      parameters:
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 发送邮箱验证码
  /user-id:
    post:
      consumes:
      - multipart/form-data
      description: 获取用户ID接口
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 用户ID不存在
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 获取用户ID
  /users/{user_id}:
    delete:
      consumes:
      - multipart/form-data
      description: 删除用户接口
      parameters:
      - description: 用户ID
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 删除用户
    get:
      consumes:
      - multipart/form-data
      description: 获取用户详细信息接口
      parameters:
      - description: 用户ID
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 获取用户详细信息
    put:
      consumes:
      - multipart/form-data
      description: 更新用户详细信息接口
      parameters:
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      - description: 用户密码
        in: formData
        name: password
        type: string
      - description: 用户邮箱
        in: formData
        name: email
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller._Response'
      summary: 更新用户详细信息
swagger: "2.0"
